name: Build and test
on: [pull_request, push]

jobs:
  build-n-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ada-actions/toolchain@ce2020
      with:
        distrib: community
    - name: Install Python 3.x (required for the testsuite)
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - run: gprbuild -Pada_toml -p -j0
    - run: gprbuild -Pcheckers -p -j0

    - run: pip install e3-testsuite
    - run: ./run-tests.py -E
